//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenjualanBarang
    {
        public int IDPenjualan { get; set; }
        public int IDproduk { get; set; }
        public int JumlahBarang { get; set; }
        public decimal HargaProduk { get; set; }
        public System.DateTime TanggalPembelian { get; set; }
        public string JenisPembayaran { get; set; }
        public int IDCustomer { get; set; }
        public int IDStaff { get; set; }
        public int IDExpedisi { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Expedisi Expedisi { get; set; }
        public virtual Produk Produk { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
